# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = -91
[main.params]
icon = "home"
newtab = false


[[main]]
identifier = "projects"
name = "Projects"
url = "/project"
weight = -90
[main.params]
icon = "code"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jcalado"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/jcalado"

[social.params]
icon = "brand-twitter"